create table public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_first text null,
  name_last text null,
  seq bigint not null,
  appt_time text null,
  status text null,
  constraint clients_pkey primary key (id),
  -- Deferrable so the reorder RPC can swap seq values in one statement
  -- without hitting temporary constraint violations.
  constraint clients_seq_unique unique (seq) deferrable initially deferred
) tablespace pg_default;

alter table public.clients enable row level security;

create policy "anon select"
on public.clients
for select
to anon
using (true);

create policy "authenticated all"
on public.clients
to authenticated
using (true)
with check (true);

-- Include full row data in UPDATE payloads so realtime subscribers see the new values.
alter table public.clients replica identity full;
-- Add to the realtime publication so changes are broadcast to subscribers.
alter publication supabase_realtime add table public.clients;

-- Atomically reorder all rows in a single UPDATE statement.
-- security invoker: runs as the calling user so RLS applies normally.
create or replace function reorder_clients(reorder_data jsonb)
returns void
language plpgsql
security invoker
as $$
begin
  update public.clients c
  set seq = (d.value->>'seq')::bigint
  from jsonb_array_elements(reorder_data) d
  where c.id = (d.value->>'id')::bigint;
end;
$$;

grant execute on function reorder_clients(jsonb) to authenticated;

-- Single-row settings table for display state.
create table public.settings (
  id int not null default 1,
  closed boolean not null default false,
  closed_message text not null default 'We''ll be right back!',
  constraint settings_pkey primary key (id),
  constraint settings_single_row check (id = 1)
);

insert into public.settings (id) values (1);

alter table public.settings enable row level security;

create policy "anon select"
on public.settings
for select
to anon
using (true);

create policy "authenticated all"
on public.settings
to authenticated
using (true)
with check (true);

-- Include full row data in UPDATE payloads so realtime subscribers see the new values.
alter table public.settings replica identity full;
-- Add to the realtime publication so changes are broadcast to subscribers.
alter publication supabase_realtime add table public.settings;
