-- ============================================================
-- CES Waiting Room - Supabase Backend Setup
-- This script is idempotent and can be run multiple times.
-- ============================================================

-- 1. Tables
-- ------------------------------------------------------------

-- Clients Table
create table if not exists public.clients (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name_first text null,
  name_last text null,
  seq bigint not null,
  appt_time text null,
  status text null,
  constraint clients_pkey primary key (id)
);

-- Ensure seq unique constraint (deferrable for reordering)
do $$ 
begin
  if not exists (select 1 from pg_constraint where conname = 'clients_seq_unique') then
    alter table public.clients add constraint clients_seq_unique unique (seq) deferrable initially deferred;
  end if;
end $$;

-- Settings Table
create table if not exists public.settings (
  id int not null default 1,
  closed boolean not null default false,
  closed_message text not null default 'We''ll be right back!',
  constraint settings_pkey primary key (id)
);

-- Ensure settings is single-row
do $$ 
begin
  if not exists (select 1 from pg_constraint where conname = 'settings_single_row') then
    alter table public.settings add constraint settings_single_row check (id = 1);
  end if;
end $$;

-- 2. Initial Data
-- ------------------------------------------------------------
insert into public.settings (id, closed, closed_message)
values (1, false, 'We''ll be right back!')
on conflict (id) do nothing;

-- 3. Functions & Triggers
-- ------------------------------------------------------------

-- Automatic sequence logic: ensures every new client gets the next available 
-- sequence number if one isn't provided.
create or replace function public.set_client_seq()
returns trigger as $$
begin
  if new.seq is null then
    new.seq := (select coalesce(max(seq), 0) + 1 from public.clients);
  end if;
  return new;
end;
$$ language plpgsql;

-- Trigger for sequence (Drop first to avoid duplication)
drop trigger if exists tr_set_client_seq on public.clients;
create trigger tr_set_client_seq
  before insert on public.clients
  for each row execute function public.set_client_seq();

-- Atomically reorder all rows in a single UPDATE statement.
-- security invoker: runs as the calling user so RLS applies normally.
create or replace function public.reorder_clients(reorder_data jsonb)
returns void
language plpgsql
security invoker
as $$
begin
  update public.clients c
  set seq = (d.value->>'seq')::bigint
  from jsonb_array_elements(reorder_data) d
  where c.id = (d.value->>'id')::bigint;
end;
$$;

-- 4. Security (RLS & Policies)
-- ------------------------------------------------------------

alter table public.clients enable row level security;
alter table public.settings enable row level security;

-- Clients Policies
drop policy if exists "anon select" on public.clients;
create policy "anon select" on public.clients for select to anon using (true);

drop policy if exists "authenticated all" on public.clients;
create policy "authenticated all" on public.clients to authenticated using (true) with check (true);

-- Settings Policies
drop policy if exists "anon select" on public.settings;
create policy "anon select" on public.settings for select to anon using (true);

drop policy if exists "authenticated all" on public.settings;
create policy "authenticated all" on public.settings to authenticated using (true) with check (true);

-- Permissions
grant execute on function public.reorder_clients(jsonb) to authenticated;

-- 5. Realtime Configuration
-- ------------------------------------------------------------

-- Include full row data in UPDATE payloads so realtime subscribers see the new values.
alter table public.clients replica identity full;
alter table public.settings replica identity full;

-- Create publication if it doesn't exist, or just ensure tables are added.
-- In Supabase, the 'supabase_realtime' publication usually already exists.
do $$
begin
  if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    create publication supabase_realtime;
  end if;
end $$;

-- Add tables to publication safely
do $$
begin
  -- Add clients table if not already present
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' 
    and schemaname = 'public' 
    and tablename = 'clients'
  ) then
    alter publication supabase_realtime add table public.clients;
  end if;

  -- Add settings table if not already present
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' 
    and schemaname = 'public' 
    and tablename = 'settings'
  ) then
    alter publication supabase_realtime add table public.settings;
  end if;
end $$;
